### ISSUE TITLE
Dependabot: Group PRs

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/cookiecutter-python#11]
Each Dependabot stanza can take a `groups:` object, which rolls matching dependency updates into a single "bundled" PR.

For example:

```yaml
- package-ecosystem: pip
  directory: /
  schedule:
    interval: daily
  groups:
    python:
      patterns:
        - "*"
```

The generated project's `dependabot.yml` should use these, probably with `actions` and `python` groups.
